#############################################################################
# Generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#  Mar 01, 2022 11:04:21 AM GMT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {Lucida Console} -size 9"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {Segoe UI} -size 9 -slant italic"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #fffaf0
set vTcl(actual_gui_fg) #2208cc
set vTcl(actual_gui_analog) #fff2f0
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #c9c9c9 -highlightbackground #f0f0f0f0f0f0 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 415x537+758+160
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "WordPie"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "WordPie" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 295 -highlightbackground #f2f2f2 -highlightcolor black \
        -width 300 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "WordPie" 1
    set site_3_0 $top.fra46
    entry $site_3_0.ent46 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord11 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent46" "txtWord11" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent48 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord13 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent48" "txtWord13" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord14 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent49" "txtWord14" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent50 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord15 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent50" "txtWord15" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab52 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Attempt 1 :} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label3" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab54 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Attempt 2 :} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label4" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab55 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Attempt 3 :} 
    vTcl:DefineAlias "$site_3_0.lab55" "Label5" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab56 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Attempt 4 :} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label6" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab57 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Attempt 5 :} 
    vTcl:DefineAlias "$site_3_0.lab57" "Label7" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab58 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Attempt 6 :} 
    vTcl:DefineAlias "$site_3_0.lab58" "Label8" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent59 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord21 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent59" "txtWord21" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord31 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent60" "txtWord31" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent61 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord41 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent61" "txtWord41" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent62 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord51 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent62" "txtWord51" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent63 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord61 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent63" "txtWord61" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent65 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord12 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent65" "txtWord12" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent66 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord22 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent66" "txtWord22" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent67 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord23 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent67" "txtWord23" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent68 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord24 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent68" "txtWord24" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent69 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord25 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent69" "txtWord25" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent47 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord32 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent47" "txtWord32" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent51 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord33 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent51" "txtWord33" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord34 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent52" "txtWord34" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent53 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord35 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent53" "txtWord35" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent54 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord42 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent54" "txtWord42" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent55 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord43 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent55" "txtWord43" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent56 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord44 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent56" "txtWord44" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent57 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord45 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent57" "txtWord45" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent64 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord52 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent64" "txtWord52" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent70 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord53 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent70" "txtWord53" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent71 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord54 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent71" "txtWord54" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent72 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord55 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent72" "txtWord55" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent74 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord62 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent74" "txtWord62" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent75 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord63 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent75" "txtWord63" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent76 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord64 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent76" "txtWord64" vTcl:WidgetProc "WordPie" 1
    entry $site_3_0.ent77 \
        -background white -disabledforeground #b6b6b6 \
        -font {-family {Lucida Console} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ff0000 \
        -highlightcolor #ff0000 -insertbackground black -justify center \
        -selectbackground blue -selectforeground white \
        -textvariable vtxtWord65 -validate key -validatecommand {vcmd %P} \
        -width 10 
    vTcl:DefineAlias "$site_3_0.ent77" "txtWord65" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab79 \
        -activebackground #ffffff -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 \
        -font {-family {Segoe UI} -size 10 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #e4715c -highlightbackground #f2f2f2 \
        -highlightcolor black \
        -text {A message saying that you've won or lost,.} -wraplength 270 
    vTcl:DefineAlias "$site_3_0.lab79" "lblMessage" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab47 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground #008000 -highlightbackground #f2f2f2 \
        -highlightcolor black -text {Grey - letter is not in the word} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label9" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab48 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground #008000 -highlightbackground #f2f2f2 \
        -highlightcolor black \
        -text {Yellow - letter is in the word but not at this position} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label9_1" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab49 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground #008000 -highlightbackground #f2f2f2 \
        -highlightcolor black \
        -text {Greeen - letter is in the word at this position} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label9_1_1" vTcl:WidgetProc "WordPie" 1
    place $site_3_0.ent46 \
        -in $site_3_0 -x 90 -y 25 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 151 -y 25 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 182 -y 25 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 215 -y 25 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 20 -y 26 -width 65 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 18 -y 58 -width 65 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 18 -y 90 -width 65 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 17 -y 121 -width 65 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 16 -y 152 -width 65 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 15 -y 183 -width 65 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 89 -y 56 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 88 -y 87 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 87 -y 118 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent62 \
        -in $site_3_0 -x 86 -y 149 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 85 -y 180 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 121 -y 25 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 120 -y 57 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 151 -y 56 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent68 \
        -in $site_3_0 -x 182 -y 55 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 215 -y 55 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 119 -y 87 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent51 \
        -in $site_3_0 -x 151 -y 87 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 181 -y 86 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent53 \
        -in $site_3_0 -x 214 -y 86 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 119 -y 118 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 151 -y 118 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 181 -y 118 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 214 -y 118 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 118 -y 149 -width 25 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent70 \
        -in $site_3_0 -x 151 -y 149 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent71 \
        -in $site_3_0 -x 182 -y 149 -width 25 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent72 \
        -in $site_3_0 -x 213 -y 149 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent74 \
        -in $site_3_0 -x 117 -y 180 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 151 -y 180 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent76 \
        -in $site_3_0 -x 183 -y 180 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent77 \
        -in $site_3_0 -x 214 -y 180 -width 25 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 5 -y 259 -width 288 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 19 -y 212 -width 169 -relwidth 0 -height 16 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 7 -y 228 -width 274 -relwidth 0 -height 16 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 5 -y 244 -width 244 -relwidth 0 -height 16 \
        -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab48 \
        -activebackground #c9c9c9 -activeforeground black -background #c9c9c9 \
        -compound left -disabledforeground #b6b6b6 \
        -font {-family {Segoe UI} -size 14 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #ae0000 -highlightbackground #f2f2f2 \
        -highlightcolor black -text {WordPie - a Python Word Game} 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "WordPie" 1
    frame $top.fra48 \
        -borderwidth 2 -relief groove -background #ffffff -height 95 \
        -highlightbackground #f2f2f2 -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra48" "Frame2" vTcl:WidgetProc "WordPie" 1
    set site_3_0 $top.fra48
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background #eef83f -command cmdStart_click -compound left \
        -disabledforeground #b6b6b6 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Start Game} 
    vTcl:DefineAlias "$site_3_0.but49" "cmdStart" vTcl:WidgetProc "WordPie" 1
    radiobutton $site_3_0.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Manual -value Man -variable ManAuto 
    vTcl:DefineAlias "$site_3_0.rad50" "radManual" vTcl:WidgetProc "WordPie" 1
    radiobutton $site_3_0.rad51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Auto -value Aut -variable ManAuto 
    vTcl:DefineAlias "$site_3_0.rad51" "radAuto" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background #ff7979 -command cmdExit_click -compound left \
        -disabledforeground #b6b6b6 \
        -font {-family {Segoe UI} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -pady 0 -text Exit 
    vTcl:DefineAlias "$site_3_0.but46" "cmdExit" vTcl:WidgetProc "WordPie" 1
    label $site_3_0.lab47 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background #ffffff -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #2f8039 \
        -highlightbackground #f2f2f2 -highlightcolor black \
        -text {Select the Manual option to do it yourself, or Auto to let the computer have a go. To complete a puzzle from another source, select Other.} \
        -wraplength 185 
    vTcl:DefineAlias "$site_3_0.lab47" "Label2" vTcl:WidgetProc "WordPie" 1
    radiobutton $site_3_0.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -anchor w -background #ffffff -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Other -value Oth -variable ManAuto 
    vTcl:DefineAlias "$site_3_0.rad46" "radOther" vTcl:WidgetProc "WordPie" 1
    place $site_3_0.but49 \
        -in $site_3_0 -x 15 -y 17 -width 90 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 119 -y 13 -width 68 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 119 -y 36 -width 54 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 15 -y 55 -width 90 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 199 -y 12 -width 189 -relwidth 0 -height 71 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad46 \
        -in $site_3_0 -x 119 -y 59 -width 54 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -relief groove -background #c9c9c9 -height 40 \
        -highlightbackground #f2f2f2 -highlightcolor black -width 310 
    vTcl:DefineAlias "$top.fra47" "Frame3" vTcl:WidgetProc "WordPie" 1
    set site_3_0 $top.fra47
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('q') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Q 
    vTcl:DefineAlias "$site_3_0.but49" "cmdQ" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('w') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text W 
    vTcl:DefineAlias "$site_3_0.but46" "cmdW" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('e') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text E 
    vTcl:DefineAlias "$site_3_0.but47" "cmdE" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('r') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text R 
    vTcl:DefineAlias "$site_3_0.but48" "cmdR" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('t') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text T 
    vTcl:DefineAlias "$site_3_0.but50" "cmdT" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('y') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Y 
    vTcl:DefineAlias "$site_3_0.but51" "cmdY" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('u') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text U 
    vTcl:DefineAlias "$site_3_0.but52" "cmdU" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('o') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text O 
    vTcl:DefineAlias "$site_3_0.but53" "cmdO" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('i') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text I 
    vTcl:DefineAlias "$site_3_0.but54" "cmdI" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('p') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text P 
    vTcl:DefineAlias "$site_3_0.but55" "cmdP" vTcl:WidgetProc "WordPie" 1
    place $site_3_0.but49 \
        -in $site_3_0 -x 7 -y 7 -width 24 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 37 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 67 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 97 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 127 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 157 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 187 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 245 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 216 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 275 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra56 \
        -relief groove -background #c9c9c9 -height 40 \
        -highlightbackground #f2f2f2 -highlightcolor black -width 280 
    vTcl:DefineAlias "$top.fra56" "Frame4" vTcl:WidgetProc "WordPie" 1
    set site_3_0 $top.fra56
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('a') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text A 
    vTcl:DefineAlias "$site_3_0.but49" "cmdA" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('s') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text S 
    vTcl:DefineAlias "$site_3_0.but46" "cmdS" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('d') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text D 
    vTcl:DefineAlias "$site_3_0.but47" "cmdD" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('f') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text F 
    vTcl:DefineAlias "$site_3_0.but48" "cmdF" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('g') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text G 
    vTcl:DefineAlias "$site_3_0.but50" "cmdG" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('h') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text H 
    vTcl:DefineAlias "$site_3_0.but51" "cmdH" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('j') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text J 
    vTcl:DefineAlias "$site_3_0.but52" "cmdJ" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('l') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text L 
    vTcl:DefineAlias "$site_3_0.but53" "cmdL" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('k') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text K 
    vTcl:DefineAlias "$site_3_0.but54" "cmdK" vTcl:WidgetProc "WordPie" 1
    place $site_3_0.but49 \
        -in $site_3_0 -x 7 -y 7 -width 24 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 37 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 67 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 97 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 127 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 157 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 187 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 248 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 217 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra57 \
        -relief groove -background #c9c9c9 -height 40 \
        -highlightbackground #f2f2f2 -highlightcolor black -width 215 
    vTcl:DefineAlias "$top.fra57" "Frame5" vTcl:WidgetProc "WordPie" 1
    set site_3_0 $top.fra57
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('z') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Z 
    vTcl:DefineAlias "$site_3_0.but49" "cmdZ" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('x') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text X 
    vTcl:DefineAlias "$site_3_0.but46" "cmdX" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('c') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text C 
    vTcl:DefineAlias "$site_3_0.but47" "cmdC" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('v') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text V 
    vTcl:DefineAlias "$site_3_0.but48" "cmdV" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('b') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text B 
    vTcl:DefineAlias "$site_3_0.but50" "cmdB" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('n') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text N 
    vTcl:DefineAlias "$site_3_0.but51" "cmdN" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdKeyboard_click('m') \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text M 
    vTcl:DefineAlias "$site_3_0.but54" "cmdM" vTcl:WidgetProc "WordPie" 1
    place $site_3_0.but49 \
        -in $site_3_0 -x 7 -y 7 -width 24 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 37 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 67 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 97 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 127 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 157 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 187 -y 7 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdEnter_click \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Enter 
    vTcl:DefineAlias "$top.but46" "cmdEnter" vTcl:WidgetProc "WordPie" 1
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdDelete_click \
        -compound left -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Delete 
    vTcl:DefineAlias "$top.but47" "cmdDelete" vTcl:WidgetProc "WordPie" 1
    frame $top.fra49 \
        -relief groove -background #c9c9c9 -height 230 \
        -highlightbackground #f2f2f2 -highlightcolor black -width 80 
    vTcl:DefineAlias "$top.fra49" "frmColours" vTcl:WidgetProc "WordPie" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab46 \
        -activebackground #ffffff -activeforeground black -anchor w \
        -background #c9c9c9 -compound left -disabledforeground #c9c9c9 \
        -font $vTcl(actual_gui_font_dft_desc) -foreground #bb0000 \
        -highlightbackground #f2f2f2 -highlightcolor black \
        -text {Click to add a colour to the highlighted letter} \
        -wraplength 80 
    vTcl:DefineAlias "$site_3_0.lab46" "lblColours" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background #72f863 -command cmdGreen_click -compound left \
        -disabledforeground #b6b6b6 -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but47" "cmdGreen" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background #ffff00 -command cmdGold_click -compound left \
        -cursor arrow -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but48" "cmdGold" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background #9f9f9f -command cmdGray_click -compound left \
        -cursor arrow -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but49" "cmdGray" vTcl:WidgetProc "WordPie" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #2208cc \
        -background $vTcl(actual_gui_bg) -command cmdNext_click \
        -compound left -cursor arrow -disabledforeground #b6b6b6 \
        -font $vTcl(actual_gui_font_dft_desc) \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Next 
    vTcl:DefineAlias "$site_3_0.but46" "cmdNext" vTcl:WidgetProc "WordPie" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 5 -y 5 -width 85 -relwidth 0 -height 61 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 28 -y 75 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 28 -y 105 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 28 -y 135 -width 24 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 20 -y 175 -width 40 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 21 -y 136 -width 300 -relwidth 0 -height 295 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 24 -y 6 -width 387 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 6 -y 37 -width 405 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 18 -y 433 -width 310 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra56 \
        -in $top -x 32 -y 465 -width 280 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra57 \
        -in $top -x 51 -y 497 -width 215 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 13 -y 504 -width 40 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 268 -y 504 -width 45 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 326 -y 142 -width 80 -relwidth 0 -height 230 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}
proc vcmd {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

